os: linux
dist: trusty
services: docker

branches:
  only:
  - parallel

env:
  global:
    - BASE=unifem/cht-coupler:mapper-dev

before_script:
  - docker --version
  - docker pull $BASE

script:
  - docker build --file docker/Dockerfile .
