os: linux
dist: trusty
services: docker

branches:
  only:
  - parallel
  - dev

env:
  global:
    - BASE=unifem/cht-coupler:mapper-dev

before_script:
  - docker --version
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker pull $BASE

script:
  - if [ "$TRAVIS_BRANCH" = "parallel" ]; then docker build --build-arg BRANCH=parallel --tag $DOCKER_USER/dtk:latest --file docker/Dockerfile .; fi
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then docker build --build-arg BRANCH=dev --tag $DOCKER_USER/dtk:dev --file docker/Dockerfile .; fi
  - docker push $DOCKER_USER/dtk
